### ISSUE TITLE
Reading function

### ISSUE THREAD

**Issue by jamboee** [RadPattern/RadPattern2017#24]
1)If given the wrong file. it should exit right away. i.e we need to check the existence of the file.
 2) checking the validity of data in the file given. invalid data, exit right away.

**Comment by YixinZhang92** [comment]
Right, I have written down all points that Ricardo said for read in file. I am working on it. Thanks for bringing it up.

Best,
Yixin

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamboee** [comment]
oh ok. sorry. Let me close it then.

**Comment by YixinZhang92** [comment]
It's ok, it can push me to solve it asap. Lol.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamboee** [comment]
Not really. coz it's not needed to what I'm working on right now.
