### ISSUE TITLE
Couple of things left

### ISSUE THREAD

**Issue by oluwaseunfadugba** [RadPattern/RadPattern2017#50]
Ni hao,

How are you? I just wanted to summarize the things that I think are left for us to do in this project. They are:

1. Display function to create plots of the radiation pattern for the different wave types.
2. Movie plot of the displacement field as it changes with time.
3. MPI

Please let me know if you have any additions and suggestions of what you can do.

Cheers.
Oluwaseun

**Comment by YixinZhang92** [comment]
Hi,

I remembered that Ricardo told us to not worry about display pictures, he said we only need to make files that can be used for displaying.

For now, I think we have done that part, we have all data that can be used for plotting (by using matlab or python).

Yes, we might need to get MPI done...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamboee** [comment]
I agree with @YixinZhang92

**Comment by oluwaseunfadugba** [comment]
Oh nice!

**Comment by oluwaseunfadugba** [comment]
Do you guys want me to work on the MPI? or any volunteer??

**Comment by YixinZhang92** [comment]
I was studying MPI yesterday, but I still don't know how to make it work... 

Just wanna make sure what Ricardo said in class: "by the end of tomorrow, we need to get the code done without MPI, and if we make it parallelized by Monday, we can get credits"?

If so, I can start to do it on Sunday, because I have a term paper due Monday.  :..(

**Comment by oluwaseunfadugba** [comment]
Oh okay. If you want, I can work on it today-tomorrow.

**Comment by jamboee** [comment]
how we are going to implement the new code in our project is a problem.

**Comment by oluwaseunfadugba** [comment]
The plan is to divide the domain into 4 and use different processors for each domain.

**Comment by YixinZhang92** [comment]
Parallel our program is not a hard problem conceptually. Use one processor do the read in, and them we just give the reading info to every processors. For example, if we have 4 processors, our research area will be devided to 4 parts equally.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YixinZhang92** [comment]
I'm Ok if we don't do MPI. But I will try on Sunday.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamboee** [comment]
we can try MPI. I will work on it in the weekend as well. if it doesn't come right away, we can abandon it.

**Comment by YixinZhang92** [comment]
The only thing we need to do is MPI, and Oluwaseun is working on that. @jamboee we can also try to work on that and see if we can help a little bit. 

The important thing is: who gonna give the talk tomorrow? As far as I know, I quit... lol

**Comment by oluwaseunfadugba** [comment]
Thanks Yixin! I can do the presentation for the group unless Eric wants to do it. 

Cheers guys and it was nice working with you.
