### ISSUE TITLE
Output filename from the user

### ISSUE THREAD

**Issue by oluwaseunfadugba** [RadPattern/RadPattern2017#53]
Ni hao Yixin,

We are still hard coding in the name of the output file. I would like the user to be able to provide it (not path please. I am not sure of how to handle that yet). Could you please add output filename to the parameters.in file. This will enable the user to be able to run multiple jobs to the HPC at the same with different output filename.

Also, I can't find our logfile and the other file using the path provided in the parameters.in file.

Thank you so much for all you do.

Cheers sis,
Oluwaseun

**Comment by YixinZhang92** [comment]
I have done that part, by writing down the path of outputfile in parameters.in, you can save your file wherever you want. I had a directory uploaded called data, which means all our output files will be saved in that directory.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by oluwaseunfadugba** [comment]
Thanks Yixin. I will check it tomorrow by God's grace. Cheers!

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 20, 2017 at 12:07 AM, YixinZhang92<notifications@github.com> wrote:   I have done that part, by writing down the path of outputfile in parameters.in, you can save your file wherever you want. I had a directory uploaded called data, which means all our output files will be saved in that directory.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
