### ISSUE TITLE
Style Consistency

### ISSUE THREAD

**Issue by ricardotaborda** [RadPattern/RadPattern2017#64]
Your code is not consistent in terms of style on the use of brackets, vertical and horizontal white spaces. There are files with incorrect indentation and so on. Make sure you have a consistent style throughout the code.

**Comment by jamboee** [comment]
Sorry, It's my bad guys. I'm going to work on this issue coz it is mostly in the functions I wrote.

**Comment by ricardotaborda** [comment]
@jamboee Not only your bad, Eric, all three should look into this.
